export const stores = [
  {
    id: "checkers",
    name: "Checkers Sixty60",
    shortName: "Sixty60",
    monogram: "60",
    loyalty: "Xtra Savings",
    color: "#00a79d",
    secondary: "#087782",
    ink: "#ffffff",
    url: "https://www.sixty60.co.za",
    domains: ["sixty60.co.za", "checkers.co.za", "shopriteholdings.co.za", "termsconditions.co.za"],
    sources: ["https://www.sixty60.co.za", "https://www.checkers.co.za/xtra-savings-plus"],
  },
  {
    id: "pnp",
    name: "Pick n Pay asap!",
    shortName: "asap!",
    monogram: "PnP",
    loyalty: "Smart Shopper",
    color: "#164da1",
    secondary: "#0c2f6a",
    ink: "#ffffff",
    url: "https://www.pnp.co.za/asap",
    domains: ["pnp.co.za"],
    sources: ["https://www.pnp.co.za/asap", "https://www.pnp.co.za/smart-shopper"],
  },
  {
    id: "woolworths",
    name: "Woolworths Dash",
    shortName: "Woolies",
    monogram: "W",
    loyalty: "MyDifference",
    color: "#292c2b",
    secondary: "#101211",
    ink: "#ffffff",
    url: "https://www.woolworths.co.za",
    domains: ["woolworths.co.za"],
    sources: [
      "https://www.woolworths.co.za/content/look/mydifference-plus-joinplus/_/A-cmp216901",
      "https://www.woolworths.co.za/content/look/dash-content-page/_/A-cmp214892",
    ],
  },
  {
    id: "shoprite",
    name: "Shoprite",
    shortName: "Shoprite",
    monogram: "S",
    loyalty: "Xtra Savings",
    color: "#df2928",
    secondary: "#a91623",
    ink: "#ffffff",
    url: "https://www.shoprite.co.za",
    domains: ["shoprite.co.za", "shopriteholdings.co.za", "termsconditions.co.za"],
    sources: ["https://www.shoprite.co.za/xtra-savings", "https://www.shoprite.co.za"],
  },
  {
    id: "spar",
    name: "SPAR2U",
    shortName: "SPAR2U",
    monogram: "S",
    loyalty: "SPAR Rewards",
    color: "#087544",
    secondary: "#06442b",
    ink: "#ffffff",
    url: "https://www.spar.co.za/spar2u",
    domains: ["spar.co.za", "spar2u.co.za"],
    sources: ["https://www.spar.co.za/spar2u", "https://www.spar.co.za/promotions"],
  },
  {
    id: "makro",
    name: "Makro",
    shortName: "Makro",
    monogram: "m",
    loyalty: "Makro Card",
    color: "#f4cb38",
    secondary: "#dba718",
    ink: "#172343",
    url: "https://www.makro.co.za",
    domains: ["makro.co.za"],
    sources: ["https://www.makro.co.za", "https://www.makro.co.za/pages/terms-of-use"],
  },
] as const;

export type Store = (typeof stores)[number];
export type StoreId = Store["id"];
export const getStore = (id: string) => stores.find((store) => store.id === id);
